version: '2.2'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    restart: always
    volumes: 
      - ./elastic_data/:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
    ports: 
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    restart: always
    depends_on: 
      - elasticsearch 
    volumes: 
     - ./utils/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment: 
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: "0.0.0.0"
    ports: 
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./utils/logstash/pipeline:/usr/share/logstash/pipeline

volumes:
  elastic_data:
